# Generated by Django 4.0.1 on 2022-01-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servivios',
            name='create',
            field=models.DateField(auto_now_add=True),
        ),
    ]
