# Generated by Django 4.0.1 on 2022-01-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosApp', '0002_alter_servivios_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servivios',
            name='imagenes',
            field=models.ImageField(upload_to='mediaServicios'),
        ),
    ]
